language: php

php:
  - 5.5

env:
    - DB=mysql db_class='Cake\Database\Driver\Mysql' db_dsn='mysql:host=0.0.0.0;dbname=todo_test' db_database='todo_test' db_username='travis' db_password='' COVERALLS=1 PHPCS=1

before_script:
  - composer install --prefer-source --no-interaction --dev

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE todo_test;'; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"
  - sh -C "if [ '$PHPCS' = '1' ]; then composer require --devcakephp/cakephp-codesniffer:dev-master; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml
  - cp config/app.php config/app_local.php
  - bin/cake migrations migrate

script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then phpcs -p --extensions=php --standard=CakePHP --ignore=vendor --ignore=tests . ; fi"

notifications:
  email: false
